
import React, { Suspense, useState } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import { Button } from '@/components/ui/button';
import { Download, ZoomIn, ZoomOut } from 'lucide-react';
import { OBJModelLoader } from './OBJModelLoader';

interface ModelViewer3DProps {
  modelUrl: string;
  onDownload?: () => void;
}

export const ModelViewer3D: React.FC<ModelViewer3DProps> = ({ 
  modelUrl, 
  onDownload 
}) => {
  const [isFullscreen, setIsFullscreen] = useState(false);

  const handleDownload = () => {
    if (onDownload) {
      onDownload();
    } else {
      // Default download behavior
      const link = document.createElement('a');
      link.href = modelUrl;
      link.download = '3d-model.zip';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  };

  return (
    <div className={`relative bg-gray-900 rounded-lg overflow-hidden ${
      isFullscreen ? 'fixed inset-0 z-50' : 'h-96'
    }`}>
      {/* 3D Canvas */}
      <Canvas
        camera={{ position: [5, 5, 5], fov: 45 }}
        className="w-full h-full"
      >
        <Suspense fallback={null}>
          {/* Lighting */}
          <ambientLight intensity={0.4} />
          <directionalLight 
            position={[10, 10, 5]} 
            intensity={1} 
            castShadow
          />
          <pointLight position={[-10, -10, -10]} intensity={0.5} />
          
          {/* 3D Model */}
          <OBJModelLoader objUrl={modelUrl} />
          
          {/* Camera Controls */}
          <OrbitControls
            enablePan={true}
            enableZoom={true}
            enableRotate={true}
            maxPolarAngle={Math.PI}
            minDistance={2}
            maxDistance={20}
          />
        </Suspense>
      </Canvas>

      {/* Control Overlay */}
      <div className="absolute top-4 right-4 flex flex-col gap-2">
        <Button
          onClick={() => setIsFullscreen(!isFullscreen)}
          size="sm"
          variant="secondary"
          className="bg-black/50 backdrop-blur-sm text-white hover:bg-black/70"
        >
          {isFullscreen ? <ZoomOut className="w-4 h-4" /> : <ZoomIn className="w-4 h-4" />}
        </Button>
        
        <Button
          onClick={handleDownload}
          size="sm"
          variant="secondary"
          className="bg-black/50 backdrop-blur-sm text-white hover:bg-black/70"
        >
          <Download className="w-4 h-4" />
        </Button>
      </div>

      {/* Instructions */}
      <div className="absolute bottom-4 left-4 text-white text-sm bg-black/50 backdrop-blur-sm rounded px-3 py-2">
        <div>🖱️ Click & drag to rotate</div>
        <div>🔍 Scroll to zoom</div>
        <div>⚡ Right-click & drag to pan</div>
      </div>

      {/* Model Info */}
      <div className="absolute top-4 left-4 text-white text-sm bg-black/50 backdrop-blur-sm rounded px-3 py-2">
        <div className="font-semibold">3D Model Viewer</div>
        <div className="text-xs text-gray-300">Generated by Hunyuan3D</div>
      </div>
    </div>
  );
};
